# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx6G
org.gradle.daemon=false

# Mod properties
mod_version = 3.0.23
mod_id = dragonlib
release_channel = beta
maven_group = de.mrjulsen.mcdragonlib
archives_name = dragonlib
enabled_platforms = fabric,neoforge
java_version = 21
datapack_version = 26

# Mod Info
display_name = DragonLib
authors = MrJulsen
description = DragonLib is a small and simple Multiloader Minecraft Library Mod based which uses architectury and adds useful tools for all my mods. This mod adds nothing special on its own. New functionality may be added at any time when needed by my mods. If you are developer feel free to use this library in your projects.
homepage = https://mrjulsen.net/mods/dragonlib/docs
issues = https://github.com/MisterJulsen/MC-DragonLib2/issues
source = https://github.com/MisterJulsen/MC-DragonLib2
license = GNU General Public License v3.0
icon = icon.png
discord = https://discord.mrjulsen.net

# Minecraft properties
minecraft_version = 1.21.1
parchment_minecraft_version = 1.21
parchment_version=2024.07.28
next_unsupported_minecraft_version=1.21.2

# Dependencies
architectury_api_version = 13.0.6
fabric_loader_version = 0.16.7
fabric_api_version = 0.102.0+1.21
neoforge_version = 21.1.72
neoforge_loader_version = 4
neoforge_dependency_version = 21.0
neoforge_config_api_port_version=21.1.1
